[[constraint]]
  name = "github.com/briandowns/spinner"
  version = "1.3.0"

[[constraint]]
  name = "github.com/c-bata/go-prompt"
  version = "0.2.2"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  version = "1.0.0"

[[constraint]]
  name = "github.com/renstrom/fuzzysearch"
  version = "1.0.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[prune]
  go-tests = true
  unused-packages = true
